name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create file for setting env vars
      # https://github.com/education/autograding/issues/69#issuecomment-1497674655
      # https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
      run: |
        echo "#!/bin/sh" > setenv.sh
        echo "export TEST_SECRET=\"${{ secrets.TEST_SECRET }}\"" >> setenv.sh
        chmod +x setenv.sh

    - name: Run tests without secret
        shell: bash
        run: |
          echo "Running fake test"

    - name: Run tests with secret
        shell: bash
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "Running tests with secret"
          bash ./setenv.sh
          bash eval/run_tests.sh "$TEST_SECRET"