name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      id: test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test
        setup-command: ''
        command: "./eval/run_tests.sh"
        timeout: 10
    - name: roy test
      id: roy-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: roy test
        setup-command: ''
        command: echo "hello roy"
        input: ''
        expected-output: hello roy
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
        ROY-TEST_RESULTS: "${{steps.roy-test.outputs.result}}"
      with:
        runners: test,roy-test
