name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print secrets
      id: print-secrets
      run: |
        echo "hello ~${{ secrets.TEST_SECRET }}~"
        echo "hello ~${{ secrets.TEST_ROY_ENV_SECRET }}~"
        echo "hello ~${{ secrets.TEST_SECRET_ROY_3 }}~"
      
    - name: Create file for setting env vars
      # https://github.com/education/autograding/issues/69#issuecomment-1497674655
      # https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
      run: |
        echo "#!/bin/sh" > setenv.sh
        # echo "export TEST_SECRET=\"${{ secrets.TEST_SECRET }}\"" >> setenv.sh
        echo "export TEST_SECRET=\"${{ secrets.TEST_ROY_ENV_SECRET }}\"" >> setenv.sh
        echo "export TEST_SECRET_ROY_3=\"${{ secrets.TEST_SECRET_ROY_3 }}\"" >> setenv.sh
        chmod +x setenv.sh

    - name: Run tests with secret
      id: eval
      shell: bash
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
        TEST_ROY_ENV_SECRET: ${{ secrets.TEST_ROY_ENV_SECRET }}
        TEST_SECRET_ROY_3: ${{ secrets.TEST_SECRET_ROY_3 }}
      run: |
        echo "Running tests with secret"
        echo "hello ~${{ secrets.TEST_SECRET }}~"
        echo "hello ~${{ secrets.TEST_ROY_ENV_SECRET }}~"
        echo "hello ~${{ secrets.TEST_SECRET_ROY_3 }}~"
        bash ./setenv.sh
        bash eval/run_tests.sh $TEST_ROY_ENV_SECRET


    - name: roy test
      id: roy-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: roy test
        setup-command: ''
        command: echo "hello roy"
        input: ''
        expected-output: hello roy
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
        ROY-TEST_RESULTS: "${{steps.roy-test.outputs.result}}"
      with:
        runners: print-secrets,eval,test,roy-test
